### ISSUE TITLE
Is there a jupyter notebook for assignment2?

### ISSUE THREAD

**Issue by nekozou** [Darrel-Koh/CSCI316GP1#46]
Is there a jupyter notebook for assignment2?

**Comment by nekozou** [comment]
hello?

**Comment by gkn0672** [comment]
Hello,

I wanted to let you know that the Assignment 2 notebook will be released after its deadline on 22nd August. I appreciate your patience and understanding while we finalize everything.

**Comment by nekozou** [comment]
Could you give me it now? I'm no method with completing it, please

**Comment by nekozou** [comment]
I don't know what to do with assignment2, please help me, I'll appreciate you very much😢.
